
window.view_SpecialSales = new database({
   tbname : 'view_SpecialSales',
   index : 'special_rule_index',
   no: 'special_no',
   clumn : {
      'special_rule_index' : 'id', 
      'special_no' : 'no', 
     // 'special_no' : 'name',
      'special_type' : 'special_type',
      'flag_integrated' : 'flag_integrated',
      'flag_integratedAmount' : 'flag_integratedAmount', 
      'flag_integratedTotal' : 'flag_integratedTotal',
      'flag_integratedCustomerLevel' : 'flag_integratedCustomerLevel',
      'flag_integratedTime' : 'flag_integratedTime',
      'flag_integratedUserestrictions' : 'flag_integratedUserestrictions',
      'flag_integratedTotalrestrictions' : 'flag_integratedTotalrestrictions',
      'flag_integratedGift' : 'flag_integratedGift',
      'flag_integratedAllowance' : 'flag_integratedAllowance',
      'flag_individualTimeout' : 'flag_individualTimeout',
      'flag_individual_min_quantity' : 'flag_individual_min_quantity',
      'flag_individual_max_quantity' : 'flag_individual_max_quantity',
      'flag_individual_item_price_flag' : 'flag_individual_item_price_flag',
      'flag_individual_alterDiscount' : 'flag_individual_alterDiscount',
      'flag_individual_alterPrice' : 'flag_individual_alterPrice',
      'require_amount' : 'require_amount',
      'require_total' : 'require_total',
      'require_customer_level' : 'require_customer_level',
      'time_start' : 'time_start',
      'time_end' : 'time_end',
      'userestrictions' : 'userestrictions',
      'totalrestrictions' : 'totalrestrictions',
      'establishdate' : 'establishdate',
      'allowance' : 'allowance',
      'individual' : 'individual',
      'active' : 'active',
      'special_rulelist_index' : 'special_rulelist_index',
      'item_id' : 'item_id',
      'require_min_quantity' : 'require_min_quantity',
      'require_max_quantity' : 'require_max_quantity',
      'timeout' : 'timeout',
      'item_price_flag' : 'item_price_flag',
      'alterDiscount' : 'alterDiscount',
      'alterPrice' : 'alterPrice',
      //'gift_id' : 'gift_id',
      //'present_total' : 'present_total'
   },
   start : 1,
   limit : 12,
   orderclumn: 'special_rule_index',
   where : 'active = 1'
});   
